import { Book, ContinueReading, Shelf } from "@/types";

export const BOOKS: Book[] = [
  {
    id: "1",
    title: "Mathematics for Secondary Schools",
    author: "Prof. James Okafor",
    cover: "https://images.unsplash.com/photo-1509228468518-180dd4864904?w=400&q=80",
    category: "Secondary",
    subcategory: "Mathematics",
    rating: 4.8,
    downloads: 42300,
    pages: 384,
    language: "English",
    publishedYear: 2023,
    description: "A comprehensive mathematics textbook covering algebra, geometry, and calculus for secondary students.",
    isFeatured: true,
    color: "#1a3a5c",
  },
  {
    id: "2",
    title: "The Adventures of Anansi",
    author: "Kwame Mensah",
    cover: "https://images.unsplash.com/photo-1533090161767-e6ffed986c88?w=400&q=80",
    category: "Story Books",
    rating: 4.9,
    downloads: 68100,
    pages: 128,
    language: "English",
    publishedYear: 2022,
    description: "Beloved African folktales featuring the clever spider Anansi, retold for modern children.",
    isFeatured: true,
    isNew: true,
    color: "#5c3a1a",
  },
  {
    id: "3",
    title: "Introduction to Python Programming",
    author: "Dr. Sarah Chen",
    cover: "https://images.unsplash.com/photo-1526379095098-d400fd0bf935?w=400&q=80",
    category: "Programming",
    rating: 4.7,
    downloads: 91200,
    pages: 512,
    language: "English",
    publishedYear: 2023,
    description: "Learn Python from scratch with practical projects and real-world examples.",
    isFeatured: true,
    color: "#1c3a1a",
  },
  {
    id: "4",
    title: "KCSE Biology Past Papers 2015–2023",
    author: "Kenya National Examinations Council",
    cover: "https://images.unsplash.com/photo-1530026405186-ed1f139313f3?w=400&q=80",
    category: "Past Papers",
    subcategory: "Biology",
    rating: 4.6,
    downloads: 134500,
    pages: 280,
    language: "English",
    publishedYear: 2023,
    description: "Complete collection of KCSE Biology past papers with marking schemes.",
    isFeatured: true,
    color: "#1a3a3a",
  },
  {
    id: "5",
    title: "Business Studies Form 3",
    author: "Margaret Wanjiku",
    cover: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=400&q=80",
    category: "High School",
    subcategory: "Business",
    rating: 4.5,
    downloads: 29800,
    pages: 256,
    language: "English",
    publishedYear: 2022,
    description: "Comprehensive business studies for Form 3 students aligned to the national curriculum.",
    color: "#3a1a1a",
  },
  {
    id: "6",
    title: "Little Explorers: My World",
    author: "Amara Joy",
    cover: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400&q=80",
    category: "Kids",
    rating: 4.9,
    downloads: 55700,
    pages: 64,
    language: "English",
    publishedYear: 2023,
    description: "A vibrant picture book helping young children discover the world around them.",
    isNew: true,
    color: "#2a1a5c",
  },
  {
    id: "7",
    title: "The Great Rift",
    author: "Ngugi wa Thiong'o",
    cover: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=400&q=80",
    category: "Novels",
    rating: 4.8,
    downloads: 77900,
    pages: 320,
    language: "English",
    publishedYear: 2021,
    description: "An epic novel set in East Africa tracing three generations of a family through turbulent times.",
    color: "#3a2a0a",
  },
  {
    id: "8",
    title: "Physics: Mechanics & Waves",
    author: "Dr. Emmanuel Osei",
    cover: "https://images.unsplash.com/photo-1636466497217-26a8cbeaf0aa?w=400&q=80",
    category: "University",
    subcategory: "Physics",
    rating: 4.6,
    downloads: 38400,
    pages: 448,
    language: "English",
    publishedYear: 2022,
    description: "University-level physics covering Newtonian mechanics, wave theory, and thermodynamics.",
    color: "#0a1a3a",
  },
  {
    id: "9",
    title: "WAEC Mathematics 2010–2023",
    author: "WAEC Council",
    cover: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=400&q=80",
    category: "Past Papers",
    subcategory: "Mathematics",
    rating: 4.7,
    downloads: 189000,
    pages: 360,
    language: "English",
    publishedYear: 2023,
    description: "Complete WAEC mathematics past papers with detailed solutions and marking schemes.",
    color: "#1a2a0a",
  },
  {
    id: "10",
    title: "Swahili Masomo: Darasa la 7",
    author: "Bi. Fatuma Hassan",
    cover: "https://images.unsplash.com/photo-1491841573634-28140fc7ced7?w=400&q=80",
    category: "Primary",
    subcategory: "Languages",
    rating: 4.5,
    downloads: 21600,
    pages: 192,
    language: "Swahili",
    publishedYear: 2022,
    description: "Vitabu vya Kiswahili kwa wanafunzi wa darasa la saba.",
    color: "#3a1a2a",
  },
  {
    id: "11",
    title: "Data Structures & Algorithms",
    author: "Thomas Korankye",
    cover: "https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=400&q=80",
    category: "Programming",
    rating: 4.9,
    downloads: 62400,
    pages: 576,
    language: "English",
    publishedYear: 2023,
    description: "Master data structures and algorithm design with real-world applications.",
    isNew: true,
    color: "#0a0a2a",
  },
  {
    id: "12",
    title: "African History: Pre-Colonial Era",
    author: "Prof. Adaeze Nwosu",
    cover: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=400&q=80",
    category: "History",
    rating: 4.7,
    downloads: 44200,
    pages: 304,
    language: "English",
    publishedYear: 2021,
    description: "A scholarly exploration of African civilizations and kingdoms before European colonization.",
    color: "#3a2a0a",
  },
  {
    id: "13",
    title: "Chemistry Form 4 Revision",
    author: "Ms. Grace Kamau",
    cover: "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=400&q=80",
    category: "High School",
    subcategory: "Chemistry",
    rating: 4.6,
    downloads: 33100,
    pages: 224,
    language: "English",
    publishedYear: 2023,
    description: "Comprehensive revision guide for Form 4 chemistry students preparing for national exams.",
    color: "#1a3a2a",
  },
  {
    id: "14",
    title: "Bedtime Tales for Little Ones",
    author: "Zara Osei",
    cover: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400&q=80",
    category: "Kids",
    rating: 4.8,
    downloads: 48900,
    pages: 96,
    language: "English",
    publishedYear: 2023,
    description: "Gentle, imaginative stories perfect for bedtime reading with young children.",
    isNew: true,
    color: "#2a0a3a",
  },
  {
    id: "15",
    title: "Entrepreneurship Fundamentals",
    author: "Dr. Kofi Acheampong",
    cover: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=400&q=80",
    category: "Business",
    rating: 4.5,
    downloads: 57300,
    pages: 288,
    language: "English",
    publishedYear: 2022,
    description: "A practical guide to starting and scaling a business in the African market.",
    color: "#3a1a0a",
  },
];

export const SHELVES: Shelf[] = [
  {
    id: "trending",
    title: "Trending Now",
    subtitle: "Most downloaded this week",
    books: BOOKS.filter((b) => b.downloads > 50000),
  },
  {
    id: "exam-resources",
    title: "Exam Resources",
    subtitle: "Ace your upcoming exams",
    books: BOOKS.filter((b) => b.category === "Past Papers" || b.subcategory === "Mathematics" || b.subcategory === "Biology"),
  },
  {
    id: "kids-corner",
    title: "Kids' Corner",
    subtitle: "Fun reads for young minds",
    books: BOOKS.filter((b) => b.category === "Kids" || b.category === "Story Books"),
  },
  {
    id: "university",
    title: "University Resources",
    subtitle: "Academic texts & references",
    books: BOOKS.filter((b) => b.category === "University" || b.category === "Programming" || b.category === "Business"),
  },
  {
    id: "recently-added",
    title: "Recently Added",
    subtitle: "Fresh content just for you",
    books: BOOKS.filter((b) => b.isNew),
  },
];

export const FEATURED_BOOKS = BOOKS.filter((b) => b.isFeatured);

export const CONTINUE_READING: ContinueReading[] = [
  {
    book: BOOKS[2],
    progress: 34,
    lastReadPage: 174,
    lastReadAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
  {
    book: BOOKS[6],
    progress: 67,
    lastReadPage: 214,
    lastReadAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
  },
];

export const CATEGORIES = [
  "All",
  "Primary",
  "Secondary",
  "High School",
  "University",
  "Kids",
  "Story Books",
  "Past Papers",
  "Novels",
  "Programming",
  "Business",
  "Science",
  "History",
  "Languages",
] as const;

export function formatDownloads(count: number): string {
  if (count >= 1000000) return `${(count / 1000000).toFixed(1)}M`;
  if (count >= 1000) return `${(count / 1000).toFixed(1)}K`;
  return count.toString();
}
